// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// This file was generated automatically.
// Please do not modify content of this file directly.
// File generated by using template: "toplevel.rs.tpl"
// To regenerate this file follow OpenTitan topgen documentations.

#![allow(dead_code)]

//! This file contains enums and consts for use within the Rust codebase.
//!
//! These definitions are for information that depends on the top-specific chip
//! configuration, which includes:
//! - Device Memory Information (for Peripherals and Memory)
//! - PLIC Interrupt ID Names and Source Mappings
//! - Alert ID Names and Source Mappings
//! - Pinmux Pin/Select Names
//! - Power Manager Wakeups

use core::convert::TryFrom;

/// Peripheral base address for dmi device on lc_ctrl in top darjeeling.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const LC_CTRL_DMI_BASE_ADDR: usize = 0x20000;

/// Peripheral size for dmi device on lc_ctrl in top darjeeling.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #LC_CTRL_DMI_BASE_ADDR and
/// `LC_CTRL_DMI_BASE_ADDR + LC_CTRL_DMI_SIZE_BYTES`.
pub const LC_CTRL_DMI_SIZE_BYTES: usize = 0x1000;

/// Peripheral base address for dbg device on rv_dm in top darjeeling.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const RV_DM_DBG_BASE_ADDR: usize = 0x0;

/// Peripheral size for dbg device on rv_dm in top darjeeling.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #RV_DM_DBG_BASE_ADDR and
/// `RV_DM_DBG_BASE_ADDR + RV_DM_DBG_SIZE_BYTES`.
pub const RV_DM_DBG_SIZE_BYTES: usize = 0x200;

/// Peripheral base address for soc device on mbx_jtag in top darjeeling.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const MBX_JTAG_SOC_BASE_ADDR: usize = 0x1000;

/// Peripheral size for soc device on mbx_jtag in top darjeeling.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #MBX_JTAG_SOC_BASE_ADDR and
/// `MBX_JTAG_SOC_BASE_ADDR + MBX_JTAG_SOC_SIZE_BYTES`.
pub const MBX_JTAG_SOC_SIZE_BYTES: usize = 0x20;

/// Peripheral base address for jtag device on soc_dbg_ctrl in top darjeeling.
///
/// This should be used with #mmio_region_from_addr to access the memory-mapped
/// registers associated with the peripheral (usually via a DIF).
pub const SOC_DBG_CTRL_JTAG_BASE_ADDR: usize = 0x2300;

/// Peripheral size for jtag device on soc_dbg_ctrl in top darjeeling.
///
/// This is the size (in bytes) of the peripheral's reserved memory area. All
/// memory-mapped registers associated with this peripheral should have an
/// address between #SOC_DBG_CTRL_JTAG_BASE_ADDR and
/// `SOC_DBG_CTRL_JTAG_BASE_ADDR + SOC_DBG_CTRL_JTAG_SIZE_BYTES`.
pub const SOC_DBG_CTRL_JTAG_SIZE_BYTES: usize = 0x20;

// PERIPH_INSEL ranges from 0 to NUM_MIO_PADS + 2 -1}
//  0 and 1 are tied to value 0 and 1
pub const NUM_MIO_PADS: usize = 12;
pub const NUM_DIO_PADS: usize = 73;

pub const PINMUX_MIO_PERIPH_INSEL_IDX_OFFSET: usize = 2;
pub const PINMUX_PERIPH_OUTSEL_IDX_OFFSET: usize = 3;

/// Pinmux Peripheral Input.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PinmuxPeripheralIn {
    /// Peripheral Input 0
    SocProxySocGpi12 = 0,
    /// Peripheral Input 1
    SocProxySocGpi13 = 1,
    /// Peripheral Input 2
    SocProxySocGpi14 = 2,
    /// Peripheral Input 3
    SocProxySocGpi15 = 3,
}

impl TryFrom<u32> for PinmuxPeripheralIn {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::SocProxySocGpi12),
            1 => Ok(Self::SocProxySocGpi13),
            2 => Ok(Self::SocProxySocGpi14),
            3 => Ok(Self::SocProxySocGpi15),
            _ => Err(val),
        }
    }
}

/// Pinmux MIO Input Selector.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PinmuxInsel {
    /// Tie constantly to zero
    ConstantZero = 0,
    /// Tie constantly to one
    ConstantOne = 1,
    /// MIO Pad 0
    Mio0 = 2,
    /// MIO Pad 1
    Mio1 = 3,
    /// MIO Pad 2
    Mio2 = 4,
    /// MIO Pad 3
    Mio3 = 5,
    /// MIO Pad 4
    Mio4 = 6,
    /// MIO Pad 5
    Mio5 = 7,
    /// MIO Pad 6
    Mio6 = 8,
    /// MIO Pad 7
    Mio7 = 9,
    /// MIO Pad 8
    Mio8 = 10,
    /// MIO Pad 9
    Mio9 = 11,
    /// MIO Pad 10
    Mio10 = 12,
    /// MIO Pad 11
    Mio11 = 13,
}

impl TryFrom<u32> for PinmuxInsel {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::ConstantZero),
            1 => Ok(Self::ConstantOne),
            2 => Ok(Self::Mio0),
            3 => Ok(Self::Mio1),
            4 => Ok(Self::Mio2),
            5 => Ok(Self::Mio3),
            6 => Ok(Self::Mio4),
            7 => Ok(Self::Mio5),
            8 => Ok(Self::Mio6),
            9 => Ok(Self::Mio7),
            10 => Ok(Self::Mio8),
            11 => Ok(Self::Mio9),
            12 => Ok(Self::Mio10),
            13 => Ok(Self::Mio11),
            _ => Err(val),
        }
    }
}

/// Pinmux MIO Output.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PinmuxMioOut {
    /// MIO Pad 0
    Mio0 = 0,
    /// MIO Pad 1
    Mio1 = 1,
    /// MIO Pad 2
    Mio2 = 2,
    /// MIO Pad 3
    Mio3 = 3,
    /// MIO Pad 4
    Mio4 = 4,
    /// MIO Pad 5
    Mio5 = 5,
    /// MIO Pad 6
    Mio6 = 6,
    /// MIO Pad 7
    Mio7 = 7,
    /// MIO Pad 8
    Mio8 = 8,
    /// MIO Pad 9
    Mio9 = 9,
    /// MIO Pad 10
    Mio10 = 10,
    /// MIO Pad 11
    Mio11 = 11,
}

impl TryFrom<u32> for PinmuxMioOut {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::Mio0),
            1 => Ok(Self::Mio1),
            2 => Ok(Self::Mio2),
            3 => Ok(Self::Mio3),
            4 => Ok(Self::Mio4),
            5 => Ok(Self::Mio5),
            6 => Ok(Self::Mio6),
            7 => Ok(Self::Mio7),
            8 => Ok(Self::Mio8),
            9 => Ok(Self::Mio9),
            10 => Ok(Self::Mio10),
            11 => Ok(Self::Mio11),
            _ => Err(val),
        }
    }
}

/// Pinmux Peripheral Output Selector.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PinmuxOutsel {
    /// Tie constantly to zero
    ConstantZero = 0,
    /// Tie constantly to one
    ConstantOne = 1,
    /// Tie constantly to high-Z
    ConstantHighZ = 2,
    /// Peripheral Output 0
    SocProxySocGpo12 = 3,
    /// Peripheral Output 1
    SocProxySocGpo13 = 4,
    /// Peripheral Output 2
    SocProxySocGpo14 = 5,
    /// Peripheral Output 3
    SocProxySocGpo15 = 6,
    /// Peripheral Output 4
    OtpCtrlTest0 = 7,
}

impl TryFrom<u32> for PinmuxOutsel {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::ConstantZero),
            1 => Ok(Self::ConstantOne),
            2 => Ok(Self::ConstantHighZ),
            3 => Ok(Self::SocProxySocGpo12),
            4 => Ok(Self::SocProxySocGpo13),
            5 => Ok(Self::SocProxySocGpo14),
            6 => Ok(Self::SocProxySocGpo15),
            7 => Ok(Self::OtpCtrlTest0),
            _ => Err(val),
        }
    }
}

/// Dedicated Pad Selects
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum DirectPads {
    SpiHost0Sd0 = 0,
    SpiHost0Sd1 = 1,
    SpiHost0Sd2 = 2,
    SpiHost0Sd3 = 3,
    SpiDeviceSd0 = 4,
    SpiDeviceSd1 = 5,
    SpiDeviceSd2 = 6,
    SpiDeviceSd3 = 7,
    I2c0Scl = 8,
    I2c0Sda = 9,
    GpioGpio0 = 10,
    GpioGpio1 = 11,
    GpioGpio2 = 12,
    GpioGpio3 = 13,
    GpioGpio4 = 14,
    GpioGpio5 = 15,
    GpioGpio6 = 16,
    GpioGpio7 = 17,
    GpioGpio8 = 18,
    GpioGpio9 = 19,
    GpioGpio10 = 20,
    GpioGpio11 = 21,
    GpioGpio12 = 22,
    GpioGpio13 = 23,
    GpioGpio14 = 24,
    GpioGpio15 = 25,
    GpioGpio16 = 26,
    GpioGpio17 = 27,
    GpioGpio18 = 28,
    GpioGpio19 = 29,
    GpioGpio20 = 30,
    GpioGpio21 = 31,
    GpioGpio22 = 32,
    GpioGpio23 = 33,
    GpioGpio24 = 34,
    GpioGpio25 = 35,
    GpioGpio26 = 36,
    GpioGpio27 = 37,
    GpioGpio28 = 38,
    GpioGpio29 = 39,
    GpioGpio30 = 40,
    GpioGpio31 = 41,
    SpiDeviceSck = 42,
    SpiDeviceCsb = 43,
    SpiDeviceTpmCsb = 44,
    Uart0Rx = 45,
    SocProxySocGpi0 = 46,
    SocProxySocGpi1 = 47,
    SocProxySocGpi2 = 48,
    SocProxySocGpi3 = 49,
    SocProxySocGpi4 = 50,
    SocProxySocGpi5 = 51,
    SocProxySocGpi6 = 52,
    SocProxySocGpi7 = 53,
    SocProxySocGpi8 = 54,
    SocProxySocGpi9 = 55,
    SocProxySocGpi10 = 56,
    SocProxySocGpi11 = 57,
    SpiHost0Sck = 58,
    SpiHost0Csb = 59,
    Uart0Tx = 60,
    SocProxySocGpo0 = 61,
    SocProxySocGpo1 = 62,
    SocProxySocGpo2 = 63,
    SocProxySocGpo3 = 64,
    SocProxySocGpo4 = 65,
    SocProxySocGpo5 = 66,
    SocProxySocGpo6 = 67,
    SocProxySocGpo7 = 68,
    SocProxySocGpo8 = 69,
    SocProxySocGpo9 = 70,
    SocProxySocGpo10 = 71,
    SocProxySocGpo11 = 72,
}

impl TryFrom<u32> for DirectPads {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::SpiHost0Sd0),
            1 => Ok(Self::SpiHost0Sd1),
            2 => Ok(Self::SpiHost0Sd2),
            3 => Ok(Self::SpiHost0Sd3),
            4 => Ok(Self::SpiDeviceSd0),
            5 => Ok(Self::SpiDeviceSd1),
            6 => Ok(Self::SpiDeviceSd2),
            7 => Ok(Self::SpiDeviceSd3),
            8 => Ok(Self::I2c0Scl),
            9 => Ok(Self::I2c0Sda),
            10 => Ok(Self::GpioGpio0),
            11 => Ok(Self::GpioGpio1),
            12 => Ok(Self::GpioGpio2),
            13 => Ok(Self::GpioGpio3),
            14 => Ok(Self::GpioGpio4),
            15 => Ok(Self::GpioGpio5),
            16 => Ok(Self::GpioGpio6),
            17 => Ok(Self::GpioGpio7),
            18 => Ok(Self::GpioGpio8),
            19 => Ok(Self::GpioGpio9),
            20 => Ok(Self::GpioGpio10),
            21 => Ok(Self::GpioGpio11),
            22 => Ok(Self::GpioGpio12),
            23 => Ok(Self::GpioGpio13),
            24 => Ok(Self::GpioGpio14),
            25 => Ok(Self::GpioGpio15),
            26 => Ok(Self::GpioGpio16),
            27 => Ok(Self::GpioGpio17),
            28 => Ok(Self::GpioGpio18),
            29 => Ok(Self::GpioGpio19),
            30 => Ok(Self::GpioGpio20),
            31 => Ok(Self::GpioGpio21),
            32 => Ok(Self::GpioGpio22),
            33 => Ok(Self::GpioGpio23),
            34 => Ok(Self::GpioGpio24),
            35 => Ok(Self::GpioGpio25),
            36 => Ok(Self::GpioGpio26),
            37 => Ok(Self::GpioGpio27),
            38 => Ok(Self::GpioGpio28),
            39 => Ok(Self::GpioGpio29),
            40 => Ok(Self::GpioGpio30),
            41 => Ok(Self::GpioGpio31),
            42 => Ok(Self::SpiDeviceSck),
            43 => Ok(Self::SpiDeviceCsb),
            44 => Ok(Self::SpiDeviceTpmCsb),
            45 => Ok(Self::Uart0Rx),
            46 => Ok(Self::SocProxySocGpi0),
            47 => Ok(Self::SocProxySocGpi1),
            48 => Ok(Self::SocProxySocGpi2),
            49 => Ok(Self::SocProxySocGpi3),
            50 => Ok(Self::SocProxySocGpi4),
            51 => Ok(Self::SocProxySocGpi5),
            52 => Ok(Self::SocProxySocGpi6),
            53 => Ok(Self::SocProxySocGpi7),
            54 => Ok(Self::SocProxySocGpi8),
            55 => Ok(Self::SocProxySocGpi9),
            56 => Ok(Self::SocProxySocGpi10),
            57 => Ok(Self::SocProxySocGpi11),
            58 => Ok(Self::SpiHost0Sck),
            59 => Ok(Self::SpiHost0Csb),
            60 => Ok(Self::Uart0Tx),
            61 => Ok(Self::SocProxySocGpo0),
            62 => Ok(Self::SocProxySocGpo1),
            63 => Ok(Self::SocProxySocGpo2),
            64 => Ok(Self::SocProxySocGpo3),
            65 => Ok(Self::SocProxySocGpo4),
            66 => Ok(Self::SocProxySocGpo5),
            67 => Ok(Self::SocProxySocGpo6),
            68 => Ok(Self::SocProxySocGpo7),
            69 => Ok(Self::SocProxySocGpo8),
            70 => Ok(Self::SocProxySocGpo9),
            71 => Ok(Self::SocProxySocGpo10),
            72 => Ok(Self::SocProxySocGpo11),
            _ => Err(val),
        }
    }
}

/// Muxed Pad Selects
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum MuxedPads {
    Mio0 = 0,
    Mio1 = 1,
    Mio2 = 2,
    Mio3 = 3,
    Mio4 = 4,
    Mio5 = 5,
    Mio6 = 6,
    Mio7 = 7,
    Mio8 = 8,
    Mio9 = 9,
    Mio10 = 10,
    Mio11 = 11,
}

impl TryFrom<u32> for MuxedPads {
    type Error = u32;
    fn try_from(val: u32) -> Result<Self, Self::Error> {
        match val {
            0 => Ok(Self::Mio0),
            1 => Ok(Self::Mio1),
            2 => Ok(Self::Mio2),
            3 => Ok(Self::Mio3),
            4 => Ok(Self::Mio4),
            5 => Ok(Self::Mio5),
            6 => Ok(Self::Mio6),
            7 => Ok(Self::Mio7),
            8 => Ok(Self::Mio8),
            9 => Ok(Self::Mio9),
            10 => Ok(Self::Mio10),
            11 => Ok(Self::Mio11),
            _ => Err(val),
        }
    }
}

/// Power Manager Wakeup Signals
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PowerManagerWakeUps {
    PinmuxAonPinWkupReq = 0,
    AonTimerAonWkupReq = 1,
    SensorCtrlWkupReq = 2,
    SocProxyWkupInternalReq = 3,
    SocProxyWkupExternalReq = 4,
}

/// Reset Manager Software Controlled Resets
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum ResetManagerSwResets {
    SpiDevice = 0,
    SpiHost0 = 1,
    I2c0 = 2,
}

/// Power Manager Reset Request Signals
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum PowerManagerResetRequests {
    AonTimerAonAonTimerRstReq = 0,
    SocProxyRstReqExternal = 1,
}

/// Clock Manager Software-Controlled ("Gated") Clocks.
///
/// The Software has full control over these clocks.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum GateableClocks {
    /// Clock clk_io_div4_peri in group peri
    IoDiv4Peri = 0,
    /// Clock clk_io_div2_peri in group peri
    IoDiv2Peri = 1,
    /// Clock clk_usb_peri in group peri
    UsbPeri = 2,
}

/// Clock Manager Software-Hinted Clocks.
///
/// The Software has partial control over these clocks. It can ask them to stop,
/// but the clock manager is in control of whether the clock actually is stopped.
#[derive(Copy, Clone, PartialEq, Eq)]
#[repr(u32)]
pub enum HintableClocks {
    /// Clock clk_main_aes in group trans
    MainAes = 0,
    /// Clock clk_main_hmac in group trans
    MainHmac = 1,
    /// Clock clk_main_kmac in group trans
    MainKmac = 2,
    /// Clock clk_main_otbn in group trans
    MainOtbn = 3,
}
