// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package bkdr_loader_reg_pkg;

  // Param list
  parameter int unsigned MaxWordWidthDiv32 = 4;
  parameter int unsigned MaxIndexBitsDiv32 = 1;

  // Address widths within the block
  parameter int RegsAw = 7;

  // Number of registers for every interface
  parameter int NumRegsRegs = 7;

  ///////////////////////////////////////////////
  // Typedefs for registers for regs interface //
  ///////////////////////////////////////////////

  typedef struct packed {
    struct packed {
      logic [7:0]  q;
    } mem_select;
    struct packed {
      logic        q;
    } issue_write;
  } bkdr_loader_reg2hw_op_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } bkdr_loader_reg2hw_data_mreg_t;

  typedef struct packed {
    logic [31:0] q;
  } bkdr_loader_reg2hw_index_mreg_t;

  typedef struct packed {
    struct packed {
      logic        d;
      logic        de;
    } issue_write;
  } bkdr_loader_hw2reg_op_reg_t;

  // Register -> HW type for regs interface
  typedef struct packed {
    bkdr_loader_reg2hw_op_reg_t op; // [168:160]
    bkdr_loader_reg2hw_data_mreg_t [3:0] data; // [159:32]
    bkdr_loader_reg2hw_index_mreg_t [0:0] index; // [31:0]
  } bkdr_loader_regs_reg2hw_t;

  // HW -> register type for regs interface
  typedef struct packed {
    bkdr_loader_hw2reg_op_reg_t op; // [1:0]
  } bkdr_loader_regs_hw2reg_t;

  // Register offsets for regs interface
  parameter logic [RegsAw-1:0] BKDR_LOADER_INFO_OFFSET = 7'h 0;
  parameter logic [RegsAw-1:0] BKDR_LOADER_OP_OFFSET = 7'h 4;
  parameter logic [RegsAw-1:0] BKDR_LOADER_DATA_0_OFFSET = 7'h 40;
  parameter logic [RegsAw-1:0] BKDR_LOADER_DATA_1_OFFSET = 7'h 44;
  parameter logic [RegsAw-1:0] BKDR_LOADER_DATA_2_OFFSET = 7'h 48;
  parameter logic [RegsAw-1:0] BKDR_LOADER_DATA_3_OFFSET = 7'h 4c;
  parameter logic [RegsAw-1:0] BKDR_LOADER_INDEX_OFFSET = 7'h 50;

  // Register index for regs interface
  typedef enum int {
    BKDR_LOADER_INFO,
    BKDR_LOADER_OP,
    BKDR_LOADER_DATA_0,
    BKDR_LOADER_DATA_1,
    BKDR_LOADER_DATA_2,
    BKDR_LOADER_DATA_3,
    BKDR_LOADER_INDEX
  } bkdr_loader_regs_id_e;

  // Register width information to check illegal writes for regs interface
  parameter logic [3:0] BKDR_LOADER_REGS_PERMIT [7] = '{
    4'b 0011, // index[0] BKDR_LOADER_INFO
    4'b 0011, // index[1] BKDR_LOADER_OP
    4'b 1111, // index[2] BKDR_LOADER_DATA_0
    4'b 1111, // index[3] BKDR_LOADER_DATA_1
    4'b 1111, // index[4] BKDR_LOADER_DATA_2
    4'b 1111, // index[5] BKDR_LOADER_DATA_3
    4'b 1111  // index[6] BKDR_LOADER_INDEX
  };

endpackage
