// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`

`include "prim_assert.sv"

module bkdr_loader_regs_reg_top (
  input clk_i,
  input rst_ni,
  input  tlul_pkg::tl_h2d_t tl_i,
  output tlul_pkg::tl_d2h_t tl_o,
  // To HW
  output bkdr_loader_reg_pkg::bkdr_loader_regs_reg2hw_t reg2hw, // Write
  input  bkdr_loader_reg_pkg::bkdr_loader_regs_hw2reg_t hw2reg, // Read

  // Integrity check errors
  output logic intg_err_o
);

  import bkdr_loader_reg_pkg::* ;

  localparam int AW = 7;
  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;
  logic reg_busy;

  tlul_pkg::tl_h2d_t tl_reg_h2d;
  tlul_pkg::tl_d2h_t tl_reg_d2h;


  // incoming payload check
  logic intg_err;
  tlul_cmd_intg_chk u_chk (
    .tl_i(tl_i),
    .err_o(intg_err)
  );

  // also check for spurious write enables
  logic reg_we_err;
  logic [6:0] reg_we_check;
  prim_reg_we_check #(
    .OneHotWidth(7)
  ) u_prim_reg_we_check (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .oh_i  (reg_we_check),
    .en_i  (reg_we && !addrmiss),
    .err_o (reg_we_err)
  );

  logic err_q;
  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      err_q <= '0;
    end else if (intg_err || reg_we_err) begin
      err_q <= 1'b1;
    end
  end

  // integrity error output is permanent and should be used for alert generation
  // register errors are transactional
  assign intg_err_o = err_q | intg_err | reg_we_err;

  // outgoing integrity generation
  tlul_pkg::tl_d2h_t tl_o_pre;
  tlul_rsp_intg_gen #(
    .EnableRspIntgGen(1),
    .EnableDataIntgGen(1)
  ) u_rsp_intg_gen (
    .tl_i(tl_o_pre),
    .tl_o(tl_o)
  );

  assign tl_reg_h2d = tl_i;
  assign tl_o_pre   = tl_reg_d2h;

  tlul_adapter_reg #(
    .RegAw(AW),
    .RegDw(DW),
    .EnableDataIntgGen(0)
  ) u_reg_if (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),

    .tl_i (tl_reg_h2d),
    .tl_o (tl_reg_d2h),

    .en_ifetch_i(prim_mubi_pkg::MuBi4False),
    .intg_error_o(),

    .we_o    (reg_we),
    .re_o    (reg_re),
    .addr_o  (reg_addr),
    .wdata_o (reg_wdata),
    .be_o    (reg_be),
    .busy_i  (reg_busy),
    .rdata_i (reg_rdata),
    .error_i (reg_error)
  );

  // cdc oversampling signals

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = addrmiss | wr_err | intg_err;

  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic [2:0] info_max_word_size_qs;
  logic [5:0] info_max_index_bits_qs;
  logic op_we;
  logic op_issue_write_qs;
  logic op_issue_write_wd;
  logic [7:0] op_mem_select_qs;
  logic [7:0] op_mem_select_wd;
  logic data_0_we;
  logic [31:0] data_0_qs;
  logic [31:0] data_0_wd;
  logic data_1_we;
  logic [31:0] data_1_qs;
  logic [31:0] data_1_wd;
  logic data_2_we;
  logic [31:0] data_2_qs;
  logic [31:0] data_2_wd;
  logic data_3_we;
  logic [31:0] data_3_qs;
  logic [31:0] data_3_wd;
  logic index_we;
  logic [31:0] index_qs;
  logic [31:0] index_wd;

  // Register instances
  // R[info]: V(False)
  //   F[max_word_size]: 2:0
  // constant-only read
  assign info_max_word_size_qs = 3'h7;

  //   F[max_index_bits]: 13:8
  // constant-only read
  assign info_max_index_bits_qs = 6'h20;


  // R[op]: V(False)
  //   F[issue_write]: 0:0
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessW1S),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_op_issue_write (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (op_we),
    .wd     (op_issue_write_wd),

    // from internal hardware
    .de     (hw2reg.op.issue_write.de),
    .d      (hw2reg.op.issue_write.d),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.op.issue_write.q),
    .ds     (),

    // to register interface (read)
    .qs     (op_issue_write_qs)
  );

  //   F[mem_select]: 15:8
  prim_subreg #(
    .DW      (8),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (8'h0),
    .Mubi    (1'b0)
  ) u_op_mem_select (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (op_we),
    .wd     (op_mem_select_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.op.mem_select.q),
    .ds     (),

    // to register interface (read)
    .qs     (op_mem_select_qs)
  );


  // Subregister 0 of Multireg data
  // R[data_0]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_data_0 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (data_0_we),
    .wd     (data_0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.data[0].q),
    .ds     (),

    // to register interface (read)
    .qs     (data_0_qs)
  );


  // Subregister 1 of Multireg data
  // R[data_1]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_data_1 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (data_1_we),
    .wd     (data_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.data[1].q),
    .ds     (),

    // to register interface (read)
    .qs     (data_1_qs)
  );


  // Subregister 2 of Multireg data
  // R[data_2]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_data_2 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (data_2_we),
    .wd     (data_2_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.data[2].q),
    .ds     (),

    // to register interface (read)
    .qs     (data_2_qs)
  );


  // Subregister 3 of Multireg data
  // R[data_3]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_data_3 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (data_3_we),
    .wd     (data_3_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.data[3].q),
    .ds     (),

    // to register interface (read)
    .qs     (data_3_qs)
  );


  // Subregister 0 of Multireg index
  // R[index]: V(False)
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_index (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (index_we),
    .wd     (index_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.index[0].q),
    .ds     (),

    // to register interface (read)
    .qs     (index_qs)
  );



  logic [6:0] addr_hit;
  always_comb begin
    addr_hit[0] = (reg_addr == BKDR_LOADER_INFO_OFFSET);
    addr_hit[1] = (reg_addr == BKDR_LOADER_OP_OFFSET);
    addr_hit[2] = (reg_addr == BKDR_LOADER_DATA_0_OFFSET);
    addr_hit[3] = (reg_addr == BKDR_LOADER_DATA_1_OFFSET);
    addr_hit[4] = (reg_addr == BKDR_LOADER_DATA_2_OFFSET);
    addr_hit[5] = (reg_addr == BKDR_LOADER_DATA_3_OFFSET);
    addr_hit[6] = (reg_addr == BKDR_LOADER_INDEX_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(BKDR_LOADER_REGS_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(BKDR_LOADER_REGS_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(BKDR_LOADER_REGS_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(BKDR_LOADER_REGS_PERMIT[3] & ~reg_be))) |
               (addr_hit[4] & (|(BKDR_LOADER_REGS_PERMIT[4] & ~reg_be))) |
               (addr_hit[5] & (|(BKDR_LOADER_REGS_PERMIT[5] & ~reg_be))) |
               (addr_hit[6] & (|(BKDR_LOADER_REGS_PERMIT[6] & ~reg_be)))));
  end

  // Generate write-enables
  assign op_we = addr_hit[1] & reg_we & !reg_error;

  assign op_issue_write_wd = reg_wdata[0];

  assign op_mem_select_wd = reg_wdata[15:8];
  assign data_0_we = addr_hit[2] & reg_we & !reg_error;

  assign data_0_wd = reg_wdata[31:0];
  assign data_1_we = addr_hit[3] & reg_we & !reg_error;

  assign data_1_wd = reg_wdata[31:0];
  assign data_2_we = addr_hit[4] & reg_we & !reg_error;

  assign data_2_wd = reg_wdata[31:0];
  assign data_3_we = addr_hit[5] & reg_we & !reg_error;

  assign data_3_wd = reg_wdata[31:0];
  assign index_we = addr_hit[6] & reg_we & !reg_error;

  assign index_wd = reg_wdata[31:0];

  // Assign write-enables to checker logic vector.
  always_comb begin
    reg_we_check[0] = 1'b0;
    reg_we_check[1] = op_we;
    reg_we_check[2] = data_0_we;
    reg_we_check[3] = data_1_we;
    reg_we_check[4] = data_2_we;
    reg_we_check[5] = data_3_we;
    reg_we_check[6] = index_we;
  end

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[2:0] = info_max_word_size_qs;
        reg_rdata_next[13:8] = info_max_index_bits_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[0] = op_issue_write_qs;
        reg_rdata_next[15:8] = op_mem_select_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[31:0] = data_0_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[31:0] = data_1_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[31:0] = data_2_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[31:0] = data_3_qs;
      end

      addr_hit[6]: begin
        reg_rdata_next[31:0] = index_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // shadow busy
  logic shadow_busy;
  assign shadow_busy = 1'b0;

  // register busy
  assign reg_busy = shadow_busy;

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT_PULSE(wePulse, reg_we, clk_i, !rst_ni)
  `ASSERT_PULSE(rePulse, reg_re, clk_i, !rst_ni)

  `ASSERT(reAfterRv, $rose(reg_re || reg_we) |=> tl_o_pre.d_valid, clk_i, !rst_ni)

  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit), clk_i, !rst_ni)

  // this is formulated as an assumption such that the FPV testbenches do disprove this
  // property by mistake
  //`ASSUME(reqParity, tl_reg_h2d.a_valid |-> tl_reg_h2d.a_user.chk_en == tlul_pkg::CheckDis)

endmodule
