// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package bkdr_loader_pkg;

  import bkdr_loader_reg_pkg::*;

  localparam int unsigned MaxWordWidth = 32*MaxWordWidthDiv32;
  localparam int unsigned MaxIndexBits = 32*MaxIndexBitsDiv32;

  // Support a maximum of 128-bit words for backdoor loading.
  typedef struct packed {
    logic                    clk;
    logic                    req;
    logic                    write;
    logic [MaxIndexBits-1:0] addr;
    logic [MaxWordWidth-1:0] wdata;
  } bkdr_req_t;

endpackage
